//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAboutme
    {
        public int AboutmeID { get; set; }
        public string AboutmeName { get; set; }
        public string AboutmeDetail { get; set; }
        public string AboutmePhone { get; set; }
        public string AboutmeEmail { get; set; }
        public string AboutmeLocation { get; set; }
        public string VideoTitle1 { get; set; }
        public string VideoTitle2 { get; set; }
        public string VideoURL { get; set; }
    }
}
